name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # egbruiken v3, als je een action van externe gebruikt, code nakijken en commit hash gebruiken
      - run: echo "$(cat hello_world.txt)"
